function renderDataTable(div, data,columns, table,options){
    if(table !== undefined){
        table.fnDestroy();
        $('#'+div).empty();
    }
    var defaults = {
        "data": data,
        "columns": columns,
        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
        "t" +
        "<'dt-toolbar-footer'<'footer'><'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
        "oTableTools": {
            "aButtons": [
                "copy",
                "csv",
                "xls",
                {
                    "sExtends": "pdf",
                    "sTitle": "Test_PDF",
                    "sPdfMessage": "easyinsight PDF Export",
                    "sPdfSize": "letter"
                },
                {
                    "sExtends": "print",
                    "sMessage": "Generated by easyinsight <i>(press Esc to close)</i>"
                }
            ],
            "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
        },
        "bDestroy": true,
        "sPaginationType": "full_numbers",
        "deferRender": true,
        "scrollX": false
    };
    var datatable = jQuery.extend({}, defaults, options);
    return $('#'+div).dataTable(datatable);
}